name: site-name
recipe: pantheon
config:
  framework: drupal10
  site: site-name
  id: site-uuid
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "site-url"
  # push: disabled 
	# pull: 
	# 	description: Pull database and files without code 
	# 		options: 
	# 			code: 
	# 				default: none
